name: Publish to PyPI
on:
  release:
    types: [published]
jobs:
  pypi_release:
    name: Builds Using UV and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Build the project
        run: uv build
      - name: Publish package
        run: uv publish
      - name: Minimize uv cache
        run: uv cache prune --ci
